# Generated by Django 3.1.7 on 2021-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=12)),
                ('state', models.CharField(choices=[('channi', 'channi'), ('west bengal', 'west bengal'), ('gujrat', 'gujrat'), ('mumbai', 'mumbai')], max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
            ],
        ),
    ]
