# Generated by Django 3.1.7 on 2021-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210309_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='DOB',
            field=models.DateTimeField(max_length=20),
        ),
    ]
