# Generated by Django 3.1.7 on 2021-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210309_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='DOB',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(default='', upload_to='pics/products/'),
        ),
    ]
